"""Add status to Recipe

Revision ID: 03da1e46c9a5
Revises: e5a1b3c7d9f2
Create Date: 2026-04-20 15:44:03.413840

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "03da1e46c9a5"
down_revision = "e5a1b3c7d9f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("status", sa.String(length=20), nullable=False, server_default="ready")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
