"""add slug and is_public to recipe

Revision ID: fc014cd27ab4
Revises: e5a1b3c7d9f2
Create Date: 2026-04-18 21:22:30.241130

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "fc014cd27ab4"
down_revision = "e5a1b3c7d9f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slug", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("is_public", sa.Boolean(), server_default="0", nullable=False)
        )
        batch_op.create_index(batch_op.f("ix_recipe_slug"), ["slug"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_slug"))
        batch_op.drop_column("is_public")
        batch_op.drop_column("slug")

    # ### end Alembic commands ###
