"""add slug and is_public to recipe

Revision ID: fc014cd27ab4
Revises: e5a1b3c7d9f2
Create Date: 2026-04-18 21:22:30.241130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc014cd27ab4'
down_revision = 'e5a1b3c7d9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_recipe_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_slug'))
        batch_op.drop_column('is_public')
        batch_op.drop_column('slug')

    op.create_table('flask_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('flask_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flask_sessions_session_id'), ['session_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_flask_sessions_expiry'), ['expiry'], unique=False)

    # ### end Alembic commands ###
